package main.java.Views;

import main.java.Controllers.Database;
import main.java.Models.Car;
import main.java.Models.History;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nicholas
 */
public class CarHistory extends javax.swing.JPanel {
    
    private final Car viewCar;

    /**
     * Creates new form CarHistory
     *
     * @param viewCar
     * @param carHistory
     */
    public CarHistory(Car viewCar, History[] carHistory) {
        this.viewCar = viewCar;
        initComponents();
        jtfBodyType.setText("" + viewCar.getBody());
        jtfColor.setText(viewCar.getColor());
        jtfCylinders.setText("" + viewCar.getCylinders());
        jtfDrivetrain.setText(viewCar.getDrivetrain());
        jtfEngine.setText("" + viewCar.getEngine());
        jtfGas.setText(viewCar.getGas());
        jtfMake.setText(viewCar.getMake());
        jtfModel.setText(viewCar.getModel());
        jtfMileage.setText("" + viewCar.getMileage());
        jtfTransmission.setText(viewCar.getTransmission());
        jtfVIN.setText(viewCar.getVin());
        jtfVehicleType.setText(viewCar.getVehicleType());
        jtfYear.setText("" + viewCar.getYear());

        this.renderCarHistory(carHistory);
    }
    
    private void renderCarHistory(History[] carHistory) {
        DefaultTableModel tableModel = (DefaultTableModel) this.jtCarHistory.getModel();

        //Delete all rows
        tableModel.setRowCount(0);

        for (History history : carHistory) {
            String[] customerModel
                    = { history.readableDate, history.getDescription() };
            tableModel.addRow(customerModel);
        }

        this.jtCarHistory.setModel(tableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlBodyType = new javax.swing.JLabel();
        jlMileage = new javax.swing.JLabel();
        jtfMileage = new javax.swing.JTextField();
        jlMake = new javax.swing.JLabel();
        jlModel = new javax.swing.JLabel();
        jlYear = new javax.swing.JLabel();
        jtfYear = new javax.swing.JTextField();
        jlTransmission = new javax.swing.JLabel();
        jlEngine = new javax.swing.JLabel();
        jlDrivetrain = new javax.swing.JLabel();
        jlVIN = new javax.swing.JLabel();
        jtfVIN = new javax.swing.JTextField();
        jtfEngine = new javax.swing.JTextField();
        jlColor = new javax.swing.JLabel();
        jlCylinders = new javax.swing.JLabel();
        jtfCylinders = new javax.swing.JTextField();
        jlGas = new javax.swing.JLabel();
        jlVehicleInfomation = new javax.swing.JLabel();
        jlVehicleType = new javax.swing.JLabel();
        jtfMake = new javax.swing.JTextField();
        jtfTransmission = new javax.swing.JTextField();
        jtfModel = new javax.swing.JTextField();
        jtfDrivetrain = new javax.swing.JTextField();
        jtfBodyType = new javax.swing.JTextField();
        jtfColor = new javax.swing.JTextField();
        jtfGas = new javax.swing.JTextField();
        jtfVehicleType = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtCarHistory = new javax.swing.JTable();
        jtfCarHistoryEvent = new javax.swing.JTextField();
        jbCarHistoryEventSubmit = new javax.swing.JButton();

        setLayout(null);

        jlBodyType.setText("Body Type");
        add(jlBodyType);
        jlBodyType.setBounds(147, 129, 64, 16);

        jlMileage.setText("Mileage");
        add(jlMileage);
        jlMileage.setBounds(6, 129, 48, 16);

        jtfMileage.setEditable(false);
        add(jtfMileage);
        jtfMileage.setBounds(60, 124, 75, 26);

        jlMake.setText("Make");
        add(jlMake);
        jlMake.setBounds(6, 33, 33, 16);

        jlModel.setText("Model");
        add(jlModel);
        jlModel.setBounds(6, 65, 38, 16);

        jlYear.setText("Year");
        add(jlYear);
        jlYear.setBounds(6, 97, 27, 16);

        jtfYear.setEditable(false);
        add(jtfYear);
        jtfYear.setBounds(60, 92, 75, 26);

        jlTransmission.setText("Transmission");
        add(jlTransmission);
        jlTransmission.setBounds(148, 33, 85, 16);

        jlEngine.setText("Displacement");
        add(jlEngine);
        jlEngine.setBounds(148, 65, 86, 16);

        jlDrivetrain.setText("Drivetrain");
        add(jlDrivetrain);
        jlDrivetrain.setBounds(147, 97, 62, 16);

        jlVIN.setText("VIN #");
        add(jlVIN);
        jlVIN.setBounds(6, 161, 34, 16);

        jtfVIN.setEditable(false);
        add(jtfVIN);
        jtfVIN.setBounds(60, 156, 75, 26);

        jtfEngine.setEditable(false);
        add(jtfEngine);
        jtfEngine.setBounds(240, 60, 75, 26);

        jlColor.setText("Color");
        add(jlColor);
        jlColor.setBounds(327, 33, 34, 16);

        jlCylinders.setText("Cylinders");
        add(jlCylinders);
        jlCylinders.setBounds(327, 65, 59, 16);

        jtfCylinders.setEditable(false);
        add(jtfCylinders);
        jtfCylinders.setBounds(412, 60, 75, 26);

        jlGas.setText("Gas");
        add(jlGas);
        jlGas.setBounds(327, 97, 23, 16);

        jlVehicleInfomation.setText("Vehicle Information");
        add(jlVehicleInfomation);
        jlVehicleInfomation.setBounds(6, 6, 123, 16);

        jlVehicleType.setText("Vehicle Type");
        add(jlVehicleType);
        jlVehicleType.setBounds(327, 129, 79, 16);

        jtfMake.setEditable(false);
        add(jtfMake);
        jtfMake.setBounds(62, 28, 80, 26);

        jtfTransmission.setEditable(false);
        add(jtfTransmission);
        jtfTransmission.setBounds(240, 28, 75, 26);

        jtfModel.setEditable(false);
        add(jtfModel);
        jtfModel.setBounds(62, 60, 75, 26);

        jtfDrivetrain.setEditable(false);
        add(jtfDrivetrain);
        jtfDrivetrain.setBounds(240, 92, 75, 26);

        jtfBodyType.setEditable(false);
        add(jtfBodyType);
        jtfBodyType.setBounds(240, 124, 75, 26);

        jtfColor.setEditable(false);
        add(jtfColor);
        jtfColor.setBounds(412, 28, 75, 26);

        jtfGas.setEditable(false);
        add(jtfGas);
        jtfGas.setBounds(412, 92, 75, 26);

        jtfVehicleType.setEditable(false);
        add(jtfVehicleType);
        jtfVehicleType.setBounds(412, 124, 75, 26);

        jLabel1.setText("History");
        add(jLabel1);
        jLabel1.setBounds(6, 192, 46, 16);

        jtCarHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Date", "Description"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int row, int column) {
                return false;
            }
        });
        jScrollPane2.setViewportView(jtCarHistory);

        add(jScrollPane2);
        jScrollPane2.setBounds(18, 222, 470, 200);

        jtfCarHistoryEvent.setToolTipText("Enter car history event description here");
        add(jtfCarHistoryEvent);
        jtfCarHistoryEvent.setBounds(58, 187, 274, 26);

        jbCarHistoryEventSubmit.setText("Submit Event");
        jbCarHistoryEventSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCarHistoryEventSubmitActionPerformed(evt);
            }
        });
        add(jbCarHistoryEventSubmit);
        jbCarHistoryEventSubmit.setBounds(338, 187, 126, 29);
    }// </editor-fold>//GEN-END:initComponents

    private void jbCarHistoryEventSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCarHistoryEventSubmitActionPerformed
        String carHistoryEvent = this.jtfCarHistoryEvent.getText();
        Database database = new Database();
        database.recordCarHistory(this.viewCar, carHistoryEvent);
        History[] updatedCarHistory = database.historyForCar(viewCar);
        this.renderCarHistory(updatedCarHistory);
        this.jtfCarHistoryEvent.setText("");
    }//GEN-LAST:event_jbCarHistoryEventSubmitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbCarHistoryEventSubmit;
    private javax.swing.JLabel jlBodyType;
    private javax.swing.JLabel jlColor;
    private javax.swing.JLabel jlCylinders;
    private javax.swing.JLabel jlDrivetrain;
    private javax.swing.JLabel jlEngine;
    private javax.swing.JLabel jlGas;
    private javax.swing.JLabel jlMake;
    private javax.swing.JLabel jlMileage;
    private javax.swing.JLabel jlModel;
    private javax.swing.JLabel jlTransmission;
    private javax.swing.JLabel jlVIN;
    private javax.swing.JLabel jlVehicleInfomation;
    private javax.swing.JLabel jlVehicleType;
    private javax.swing.JLabel jlYear;
    private javax.swing.JTable jtCarHistory;
    private javax.swing.JTextField jtfBodyType;
    private javax.swing.JTextField jtfCarHistoryEvent;
    private javax.swing.JTextField jtfColor;
    private javax.swing.JTextField jtfCylinders;
    private javax.swing.JTextField jtfDrivetrain;
    private javax.swing.JTextField jtfEngine;
    private javax.swing.JTextField jtfGas;
    private javax.swing.JTextField jtfMake;
    private javax.swing.JTextField jtfMileage;
    private javax.swing.JTextField jtfModel;
    private javax.swing.JTextField jtfTransmission;
    private javax.swing.JTextField jtfVIN;
    private javax.swing.JTextField jtfVehicleType;
    private javax.swing.JTextField jtfYear;
    // End of variables declaration//GEN-END:variables
}
